GET_ELEMENT_BY_ID = "GET_ELEMENT_BY_ID"
GET_ELEMENTS_BY_CLASS_NAME = "GET_ELEMENTS_BY_CLASS_NAME"
GET_ELEMENTS_BY_TAG_NAME = "GET_ELEMENTS_BY_TAG_NAME"
QUERY_SELECTOR = "QUERY_SELECTOR"
JQUERY = "JQUERY"

# non reachable
NON_REACHABLE = "NON_REACH"

# read 
SELECTOR_RD_WIN_LOC = "SELECTOR_RD_WIN_LOC"
SELECTOR_RD_WIN_NAME = "SELECTOR_RD_WIN_NAME"
SELECTOR_RD_DOC_REF = "SELECTOR_RD_DOC_REF"
SELECTOR_RD_PM = "SELECTOR_RD_PM"
SELECTOR_RD_WEB_STORAGE = "SELECTOR_RD_WEB_STORAGE"
SELECTOR_RD_DOM_TREE = "SELECTOR_RD_DOM"
SELECTOR_RD_COOKIE = "SELECTOR_RD_COOKIE"

SELECTOR_GET_ELEMENT_BY_ID = "SELECTOR_GET_ELEMENT_BY_ID"
SELECTOR_GET_ELEMENTS_BY_CLASS_NAME = "SELECTOR_GET_ELEMENTS_BY_CLASS_NAME"
SELECTOR_GET_ELEMENTS_BY_TAG_NAME = "SELECTOR_GET_ELEMENTS_BY_TAG_NAME"
SELECTOR_QUERY_SELECTOR = "SELECTOR_QUERY_SELECTOR"
SELECTOR_JQUERY = "SELECTOR_JQUERY"
